export const AMENITIES_FILTER = 'AMENITIES_FILTER';
export const PRICE_FILTER = 'PRICE_FILTER';
export const LOCATION_FILTER = 'LOCATION_FILTER';
export const FREECANCELLATION_FILTER = 'FREECANCELLATION_FILTER';
export const ACCOMMODATION_FILTER = 'ACCOMMODATION_FILTER';