"""empty message

Revision ID: 42a7744ba0f0
Revises: 86fc71480f0a
Create Date: 2020-07-24 16:14:37.262912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a7744ba0f0'
down_revision = '86fc71480f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('image', sa.String(length=500), nullable=True))
    op.drop_column('hotels', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('img', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('hotels', 'image')
    # ### end Alembic commands ###
