"""empty message

Revision ID: 503e7994a5ef
Revises: 
Create Date: 2020-07-24 15:20:33.772667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503e7994a5ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aminities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.Column('internet', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('air_conditioning', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bedroom_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bedroom', sa.Integer(), nullable=True),
    sa.Column('guest', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('room_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('bed_price', sa.Integer(), nullable=True),
    sa.Column('aminities', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['aminities'], ['aminities.id'], ),
    sa.ForeignKeyConstraint(['bed_price'], ['bedroom_price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_o_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('expired_in', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=True),
    sa.Column('hotel_details', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('accomodation_type', sa.String(length=100), nullable=True),
    sa.Column('free_cancellation', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_details'], ['room_details.id'], ),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_details_bedroom_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_details_id', sa.Integer(), nullable=True),
    sa.Column('bedroom_price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bedroom_price_id'], ['bedroom_price.id'], ),
    sa.ForeignKeyConstraint(['room_details_id'], ['room_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_details_bedroom_price')
    op.drop_table('hotels')
    op.drop_table('user_o_auth')
    op.drop_table('room_details')
    op.drop_table('users')
    op.drop_table('location')
    op.drop_table('bedroom_price')
    op.drop_table('aminities')
    # ### end Alembic commands ###
