"""empty message

Revision ID: 5bbe1d5030da
Revises: e839bb255a34
Create Date: 2020-07-27 16:56:43.151474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbe1d5030da'
down_revision = 'e839bb255a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_details', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room_details', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_details', type_='foreignkey')
    op.drop_column('room_details', 'hotel_id')
    # ### end Alembic commands ###
