"""empty message

Revision ID: 86fc71480f0a
Revises: 61cbc0e8484d
Create Date: 2020-07-24 16:11:30.935991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86fc71480f0a'
down_revision = '61cbc0e8484d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('img', sa.String(length=255), nullable=True))
    op.drop_column('hotels', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('images', mysql.JSON(), nullable=True))
    op.drop_column('hotels', 'img')
    # ### end Alembic commands ###
