"""empty message

Revision ID: 8bdafb4e03e1
Revises: e37b400445bf
Create Date: 2020-07-24 16:00:32.845758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bdafb4e03e1'
down_revision = 'e37b400445bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'room_details', ['room_type'])
    op.drop_constraint('room_details_ibfk_2', 'room_details', type_='foreignkey')
    op.drop_column('room_details', 'bed_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_details', sa.Column('bed_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('room_details_ibfk_2', 'room_details', 'bedroom_price', ['bed_price'], ['id'])
    op.drop_constraint(None, 'room_details', type_='unique')
    # ### end Alembic commands ###
