"""empty message

Revision ID: b851c216e374
Revises: fbf4d31a0394
Create Date: 2020-07-30 10:21:37.308671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b851c216e374'
down_revision = 'fbf4d31a0394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('lati', sa.Float(precision='10,6'), nullable=True))
    op.add_column('location', sa.Column('longi', sa.Float(precision='10,6'), nullable=True))
    op.drop_column('location', 'longitude')
    op.drop_column('location', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', mysql.FLOAT(precision=8, scale=7), nullable=True))
    op.add_column('location', sa.Column('longitude', mysql.FLOAT(precision=8, scale=7), nullable=True))
    op.drop_column('location', 'longi')
    op.drop_column('location', 'lati')
    # ### end Alembic commands ###
