export const IMAGEREQUEST = "IMAGEREQUEST"
export const DATAREQUEST = "DATAREQUEST"
export const REVIEWREQUEST = "REVIEWREQUEST"

// export const APIFAILURE = "APIFAILURE"
// export const FREECANCELLATION = "FREECANCELATION"
 