export const IMAGEREQUEST = "IMAGEREQUEST"
export const DATAREQUEST = "DATAREQUEST"
export const REVIEWREQUEST = "REVIEWREQUEST"
export const RECOMMENDATIONREQUEST = "RECOMMENDATIONREQUEST"

// export const APIFAILURE = "APIFAILURE"
// export const FREECANCELLATION = "FREECANCELATION"
 